name: FATUnicorn
favicon: null
layout_spectrum: 0.3561610777396709
typography_spectrum: 0.04025637242011726
title: Welcome to FATUnicorn.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6366389156319201
  lightness: 0.0999969276599586
  saturation: 0.31021372345276177
  rhythmicContrast: 0.5168079880531877
purpose: []
